### ISSUE TITLE
circular dependency in compile_first files

### ISSUE THREAD

**Issue by josephDunne** [ubf/ubf#12] opened 2015-01-06 19:44 UTC
A clean checkout and compile of UBF results in the following error:
```
==> ubf (compile)
Compiled src/contract_lex.xrl
Compiled src/contract_yecc.yrl
Compiled src/ubf_utils.erl
Compiling src/ubf_types_builtin.erl failed:
src/ubf_types_builtin.erl:none: undefined parse transform 'contract_parser'
```

**Comment by josephDunne** [comment] 2015-01-06 19:49
```
rebar --version
rebar 2.5.1 R16B03-1 20141130_113537 git 2.5.1-51-gd42ed46
```

**Comment by norton** [comment] 2015-01-07 01:39
I *occasionally* refresh the bundled rebar escript based on this custom branch (https://github.com/norton/rebar/tree/norton-abnfc) using a two versions older version of Erlang/OTP.  I have tried with a recent version of rebar.

'''
$ ./rebar --version
rebar 2.2.0 R15B03 20140504_022950 git 2.2.0-61-g97751ec
'''

Based on the Quick Start Recipe (https://github.com/ubf/ubf/blob/master/README.md#quick-start-recipe), I see the following behavior.

'''
$ . /usr/local/Cellar/kerlang/r16b03/activate 
$ which erl
/usr/local/Cellar/kerlang/r16b03/bin/erl
$ which erlc
/usr/local/Cellar/kerlang/r16b03/bin/erlc
$ git clone https://github.com/ubf/ubf.git ubf
Cloning into 'ubf'...
remote: Counting objects: 4013, done.
remote: Total 4013 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (4013/4013), 6.96 MiB | 4.43 MiB/s, done.
Resolving deltas: 100% (2031/2031), done.
Checking connectivity... done.
$ cd ubf/
$ make deps clean compile
./rebar get-deps
WARN:  Expected /Users/norton/tmp/ubf/deps/qc to be an app dir (containing ebin/*.app), but no .app found.
WARN:  Expected /Users/norton/tmp/ubf/deps/pmod_transform to be an app dir (containing ebin/*.app), but no .app found.
==> ubf (get-deps)
WARN:  Expected /Users/norton/tmp/ubf/deps/qc to be an app dir (containing ebin/*.app), but no .app found.
WARN:  Expected /Users/norton/tmp/ubf/deps/pmod_transform to be an app dir (containing ebin/*.app), but no .app found.
Pulling qc from {git,"git://github.com/norton/qc.git"}
Cloning into 'qc'...
Pulling pmod_transform from {git,"git://github.com/ubf/pmod_transform.git"}
Cloning into 'pmod_transform'...
==> qc (get-deps)
==> pmod_transform (get-deps)
./rebar clean -r
==> qc (clean)
==> pmod_transform (clean)
==> ubf (clean)
./rebar compile
==> qc (compile)
Compiled src/qc_gen.erl
Compiled src/qc_gen_http.erl
Compiled src/qc_statem.erl
Compiled src/qc_slave.erl
Compiled src/qc.erl
==> pmod_transform (compile)
Compiled src/pmod_pt.erl
==> ubf (compile)
Compiled src/contract_lex.xrl
Compiled src/contract_yecc.yrl
Compiled src/contract_lex.erl
Compiled src/contract_yecc.erl
Compiled src/ubf_utils.erl
Compiled src/contract_parser.erl
Compiled src/ubf_types_builtin.erl
Compiled src/contracts.erl
Compiled src/ubf_plugin_handler.erl
Compiled src/proc_socket_server.erl
Compiled src/contract_proto.erl
Compiled src/contract_manager.erl
Compiled src/contract_driver.erl
Compiled src/ubf_plugin_stateless.erl
Compiled src/ubf_plugin_stateful.erl
Compiled src/ubf_server.erl
Compiled src/ubf_driver.erl
Compiled src/ubf_plugin_meta_stateless.erl
Compiled src/ubf_plugin_meta_stateful.erl
Compiled src/qc_ubf_types.erl
Compiled src/qc_ubf_impl.erl
Compiled src/qc_ubf.erl
Compiled src/proc_utils.erl
Compiled src/ebf_driver.erl
Compiled src/ubf_client.erl
Compiled src/ebf.erl
Compiled src/contracts_abnf.erl
Compiled src/ubf.erl
Compiled src/contract_manager_tlog.erl

$ ./rebar --version
rebar 2.2.0 R15B03 20140504_022950 git 2.2.0-61-g97751ec
'''

**Comment by josephDunne** [comment] 2015-01-10 18:37
ja, I don't get it. I checkout UBF and it compiles, I checkout ubf-json and it compiles. but my project which includes UBF gets the error above.

**Comment by norton** [comment] 2015-01-10 18:48
I suspect it is due to the version of rebar used by your project.  Just a guess.

**Comment by josephDunne** [comment] 2015-01-10 18:48
no its using the same (system) rebar

**Comment by josephDunne** [comment] 2015-01-10 18:49
tried multiple erlang versions

**Comment by norton** [comment] 2015-01-10 18:52
Does debug show anything?

**Comment by josephDunne** [comment] 2015-01-10 19:03
it says rebar calculates the list of dependencies and determines that bf_types_builtin should be compiled first:
```
DEBUG: Files to compile first: ["src/ubf_utils.erl",
                                "src/ubf_types_builtin.erl",
                                "src/contract_yecc.erl",
                                "src/contract_parser.erl",
                                "src/contract_lex.erl","src/contracts.erl",
                                "src/ubf_plugin_handler.erl",
                                "src/proc_socket_server.erl",
                                "src/contract_proto.erl",
                                "src/contract_manager.erl",
                                "src/contract_driver.erl"]
```

full:
```
==> ubf (compile)
DEBUG: Matched required ERTS version: 6.3 -> .*
DEBUG: Matched required OTP release: 17 -> .*
DEBUG: 17 satisfies the requirement for vsn R15
DEBUG: is_app_available, looking for App qc with Path "/Users/joe/code/pmt/git/products/number_portability/deps/qc"
INFO:  Looking for qc- ; found qc-v2.0.0 at /Users/joe/code/pmt/git/products/number_portability/deps/qc
DEBUG: is_app_available, looking for App pmod_transform with Path "/Users/joe/code/pmt/git/products/number_portability/deps/pmod_transform"
INFO:  Looking for pmod_transform- ; found pmod_transform-b59924e at /Users/joe/code/pmt/git/products/number_portability/deps/pmod_transform
DEBUG: Starting 3 compile worker(s)
DEBUG: Worker exited cleanly
DEBUG: Worker exited cleanly
INFO:  Skipped src/contract_lex.xrl
DEBUG: Worker exited cleanly
DEBUG: Starting 3 compile worker(s)
DEBUG: Worker exited cleanly
DEBUG: Worker exited cleanly
INFO:  Skipped src/contract_yecc.yrl
DEBUG: Worker exited cleanly
DEBUG: erl_opts [debug_info,warnings_as_errors,warn_shadow_vars,
                 warn_obsolete_guard]
DEBUG: Files dependent on src/ubf_server.erl: []
DEBUG: Files dependent on src/ubf_plugin_stateless.erl: []
DEBUG: Files dependent on src/ubf_plugin_stateful.erl: []
DEBUG: Files dependent on src/ubf_plugin_meta_stateless.erl: []
DEBUG: Files dependent on src/ubf_plugin_meta_stateful.erl: []
DEBUG: Files dependent on src/ubf_plugin_handler.erl:
["src/ubf_plugin_meta_stateful.erl","src/ubf_plugin_meta_stateless.erl"]
DEBUG: Files dependent on src/ubf_driver.erl: []
DEBUG: Files dependent on src/ubf_client.erl: []
DEBUG: Files dependent on src/ubf.erl: []
DEBUG: Files dependent on src/qc_ubf_types.erl: []
DEBUG: Files dependent on src/qc_ubf_impl.erl: []
DEBUG: Files dependent on src/qc_ubf.erl: []
DEBUG: Files dependent on src/proc_utils.erl: []
DEBUG: Files dependent on src/proc_socket_server.erl:
["src/ubf_server.erl"]
DEBUG: Files dependent on src/ebf_driver.erl: []
DEBUG: Files dependent on src/ebf.erl: []
DEBUG: Files dependent on src/contracts_abnf.erl: []
DEBUG: Files dependent on src/contracts.erl:
["src/ubf_client.erl","src/contract_manager.erl"]
DEBUG: Files dependent on src/contract_proto.erl:
["src/ebf.erl","src/ubf.erl"]
DEBUG: Files dependent on src/contract_manager_tlog.erl: []
DEBUG: Files dependent on src/contract_manager.erl:
["src/ubf_client.erl"]
DEBUG: Files dependent on src/contract_driver.erl:
["src/ebf_driver.erl","src/ubf_driver.erl"]
DEBUG: Files to compile first: ["src/ubf_utils.erl",
                                "src/ubf_types_builtin.erl",
                                "src/contract_yecc.erl",
                                "src/contract_parser.erl",
                                "src/contract_lex.erl","src/contracts.erl",
                                "src/ubf_plugin_handler.erl",
                                "src/proc_socket_server.erl",
                                "src/contract_proto.erl",
                                "src/contract_manager.erl",
                                "src/contract_driver.erl"]
DEBUG: Dependencies of src/ubf_utils.erl:
["include/ubf_impl.hrl","include/ubf.hrl"]
INFO:  Skipped src/ubf_utils.erl
DEBUG: Dependencies of src/ubf_types_builtin.erl:
["include/ubf_impl.hrl","src/contract_parser.erl"]
Compiling /Users/joe/code/pmt/git/products/number_portability/deps/ubf/src/ubf_types_builtin.erl failed:
/Users/joe/code/pmt/git/products/number_portability/deps/ubf/src/ubf_types_builtin.erl:none: undefined parse transform 'contract_parser'
DEBUG: Compilation failed: {error,[["/Users/joe/code/pmt/git/products/number_portability/deps/ubf/src/ubf_types_builtin.erl:none: undefined parse transform 'contract_parser'\n"]],
                                  []}
ERROR: compile failed while processing /Users/joe/code/pmt/git/products/number_portability/deps/ubf: rebar_abort
```

**Comment by norton** [comment] 2015-01-11 01:41
Hmm … appears to be a bug with rebar and lex/yecc dependencies?

What is the contents of your top-level rebar.config file?

**Comment by josephDunne** [comment] 2015-01-11 15:20
its really simple:
```
{erl_opts, [debug_info, fail_on_warning]}.
{eunit_opts, [verbose]}.

{deps, [
	{bitcask,     ".*", {git, "https://github.com/basho/bitcask.git", {tag, "1.7.1"}}},
	{ubf,         ".*", {git, "https://github.com/ubf/ubf.git", {branch, "2.2.0"}}},
	{bcrypt,      ".*", {git, "git@github.com:opscode/erlang-bcrypt.git", {tag, "0.5.0.3"}}},
	{riak_dt,     ".*", {git, "https://github.com/basho/riak_dt.git", {tag, "2.0.0"}}},
	{lager,       ".*", {git, "git://github.com/basho/lager.git", {tag, "2.0.3"}}},
	{folsom,      ".*", {git, "https://github.com/boundary/folsom.git", {branch, "master"}}},
	{cuttlefish,  ".*", {git, "git://github.com/basho/cuttlefish", {branch, "master"}}},
	{recon,       ".*", {git, "https://github.com/ferd/recon.git", {branch, "master"}}}
]}.
```

**Comment by josephDunne** [comment] 2015-01-11 17:59
I feel that having ubf_builtin_type dependant on contract_parser which in turn depends on ubf_builtin_types is a problem. Are you open to other ways of bootstrapping this? Otherwise projects are dependant on R15/your version of rebar to use this code.

**Comment by norton** [comment] 2015-01-11 18:09
Can you try adding qc as an explicit depends in your rebar.config ?

**Comment by josephDunne** [comment] 2015-01-11 18:17
i did no change

**Comment by norton** [comment] 2015-01-11 18:32
I'd like to understand why there is no issue with the ubf-jsonrpc module (and others) before making any changes. I will try to repeat your issue locally.

**Comment by josephDunne** [comment] 2015-01-11 18:36
they all use the same compiled version of rebar in the repository. i can recreate the issue in all projects using this version of rebar:
```
rebar --version
rebar 2.5.1 17 20150110_180943 git 2.5.1-92-g3288afa
```

**Comment by norton** [comment] 2015-01-11 18:38
Is your repository available to clone?

**Comment by josephDunne** [comment] 2015-01-11 18:47
no, but try this one:
https://github.com/josephDunne/ubf_issue.git

erlang r17

**Comment by norton** [comment] 2015-01-12 04:07
IMHO, this is a bug with rebar.

I added 2 extra debug statements to illustrate this point.  rebar does not maintain the order of the erl_first_files given in the rebar.config file.

````
DEBUG: erl_opts [debug_info,warnings_as_errors,warn_shadow_vars,
                 warn_obsolete_guard]
DEBUG: erl_first_files (conf) ["src/contract_lex.erl","src/contract_yecc.erl",
                               "src/ubf_utils.erl","src/contract_parser.erl",
                               "src/ubf_types_builtin.erl"]
DEBUG: erl_first_files ["src/ubf_utils.erl","src/ubf_types_builtin.erl",
                        "src/contract_yecc.erl","src/contract_parser.erl",
                        "src/contract_lex.erl"]
````

Review this snippet of code (https://github.com/rebar/rebar/blob/master/src/rebar_erlc_compiler.erl#L309-L313) and check my reasoning.

Git blame seems to point to this change (https://github.com/rebar/rebar/commit/49c25642b3da6796c05385b76160178e3c9a2c83).

If you agree, please feel free to raise this issue with rebar/rebar.

**Comment by josephDunne** [comment] 2015-01-12 11:36
Thanks for taking a look. However your branch of rebar (https://github.com/norton/rebar/tree/norton-abnfc) has those changes. I can't see where the list sort is happening. `lists:partition/2` doesn't sort its output so perhaps its somewhere else. I will need to look at rebar more before I log a issue.

UBF can't control the rebar version if its included as a dependency in other projects so I don't think its good practice to rely on a custom version of rebar for a library. For the same reason I don't understand why rebar is committed into the code base. I will have to maintain a fork of this project if my organisation is going to use it.

**Comment by norton** [comment] 2015-01-12 12:39
It is good to keep this issue open.  A new issue with rebar should be opened to address the root problem.

**Comment by norton** [comment] 2015-01-12 23:23
FYI.  I submitted an issue for rebar (rebar/rebar#429).

**Comment by norton** [comment] 2015-01-13 05:05
With regards to two of your comments, I commit a version of rebar into the UBF repository to control the version of rebar that is tested with ubf.  It helps to avoid situations like this regression.  The custom changes applied to rebar are intended for the ubf-abnf repository but I simply choose to use the same version of rebar for all of the ubf repositories.  These custom changes should not have any adverse impacts for the general user.

Once this rebar issue is fixed and merged into the rebar master branch, I expect you will be able to use the stock rebar for your own repository without any issues.  The rebar that you use in your own repository should by rebar's default behavior (if my understanding is correct) be used to build all depends of your repository.  The customized rebar contained in the ubf directory will be ignored.

Make sense?

**Comment by josephDunne** [comment] 2015-01-13 10:18
It does make sense, thank you.

**Comment by norton** [comment] 2015-02-03 01:25
This issue has been addressed by the upstream rebar.

- Please try out your own rebar based on the master branch (rebar/rebar#429).
- I also posted an updated version of rebar to the dev branch (c9d6d732).

**Comment by josephDunne** [comment] 2015-02-03 12:06
Thank you

**Comment by tatsuya6502** [comment] 2015-03-26 16:11
FYI, I ran into a similar problem and I found that upgrading rebar (as suggested) solves it.

Thank you for fixing it!

**With Older Rebar**

```sh
/usr/home/tatsuya/workhub/dev/hibari-dev/hibari% ./rebar -V
rebar 2.5.1 17 20141014_120220 git 2.5.1-17-gad3328b
/usr/home/tatsuya/workhub/dev/hibari-dev/hibari% gmake compile
compiling: hibari-0.1.11-dev-x86_64-unknown-freebsd10.0-64 ...
./rebar compile

...

==> ubf (compile)
Compiled src/contract_lex.xrl
Compiled src/contract_yecc.yrl
Compiled src/contract_yecc.erl
Compiled src/contract_parser.erl
Error in contract:{error,tokens}
Compiling /usr/home/tatsuya/workhub/dev/hibari-dev/hibari/lib/ubf/src/ubf_types_builtin.erl failed:
/usr/home/tatsuya/workhub/dev/hibari-dev/hibari/lib/ubf/src/ubf_types_builtin.erl:none: error in parse transform 'contract_parser': {{error,tokens},
                                             [{contract_parser,
                                               parse_transform,6,
                                               [{file,
                                                 "src/contract_parser.erl"},
                                                {line,115}]},
```

**With the Latest Rebar** 

```sh
/usr/home/tatsuya/workhub/dev/hibari-dev/hibari% ./rebar -V
rebar 2.5.1 17 20150326_143134 git 2.5.1-141-g02de46d
/usr/home/tatsuya/workhub/dev/hibari-dev/hibari% gmake compile     
compiling: hibari-0.1.11-dev-x86_64-unknown-freebsd10.0-64 ...
./rebar compile

...

==> ubf (compile)
Compiled src/contract_lex.xrl
Compiled src/contract_yecc.yrl
Compiled src/contract_lex.erl
Compiled src/contract_yecc.erl
Compiled src/ubf_utils.erl
Compiled src/contract_parser.erl
Compiled src/ubf_types_builtin.erl
Compiled src/contracts.erl
Compiled src/contract_driver.erl
Compiled src/ubf_plugin_handler.erl
Compiled src/contract_manager.erl
Compiled src/proc_socket_server.erl
Compiled src/contract_proto.erl
Compiled src/contract_manager_tlog.erl
Compiled src/ubf_server.erl
Compiled src/ubf_driver.erl
Compiled src/proc_utils.erl
Compiled src/qc_ubf.erl
Compiled src/ubf_plugin_stateless.erl
Compiled src/qc_ubf_impl.erl
Compiled src/ubf.erl
Compiled src/ebf.erl
Compiled src/ubf_plugin_stateful.erl
Compiled src/ebf_driver.erl
Compiled src/ubf_plugin_meta_stateless.erl
Compiled src/ubf_plugin_meta_stateful.erl
Compiled src/qc_ubf_types.erl
Compiled src/contracts_abnf.erl
Compiled src/ubf_client.erl
==> ubf_thrift (compile)
Compiled src/tbf_driver.erl
Compiled src/ftbf.erl
Compiled src/ftbf_driver.erl
Compiled src/thrift_contract_parser.erl
Compiled src/ubf_thrift_plugin.erl
Compiled src/tbf.erl
==> gdss_ubf_proto (compile)
Compiled src/ubf_gdss_plugin.erl
Compiled src/tbf_gdss_plugin.erl
Compiled src/gdss_ubf_proto.erl
Compiled src/gdss_ubf_proto_sup.erl
Compiled src/ubf_gdss_stub_plugin.erl
==> rel (compile)
==> hibari (compile)
/usr/home/tatsuya/workhub/dev/hibari-dev/hibari% 
```

**Comment by norton** [comment] 2015-03-27 02:43
Great.  @tatsuya6502 Thank you for testing.  Fix has been merged to the master branch.

**Closed by norton** 2015-03-27 02:43 UTC
